import {fileURLToPath} from "node:url";
export const PORT=Number(process.env.PORT||3000);
export const MAGIC_LINK_DAILY_LIMIT=Number(process.env.MAGIC_LINK_DAILY_LIMIT||process.env.DAILY_LOCAL_LIMIT||5);
export const PROVIDER_DAILY_REQUEST_LIMIT=Number(process.env.PROVIDER_DAILY_REQUEST_LIMIT||45);
export const PROVIDER_TIMEOUT_MS=Number(process.env.PROVIDER_TIMEOUT_MS||30000);
export const PROVIDER_MAX_RESPONSE_BYTES=Number(process.env.PROVIDER_MAX_RESPONSE_BYTES||512*1024);
export const PROVIDER_SEND_MAGICLINK_ENABLED=/^(1|true|yes|on)$/i.test(String(process.env.PROVIDER_SEND_MAGICLINK_ENABLED||"true"));
export const PROVIDER_SEND_MAGICLINK_PATH=process.env.PROVIDER_SEND_MAGICLINK_PATH||"/api/v1/send-magiclink";
export const PROVIDER_VERIFY_ACCOUNT_PATH=process.env.PROVIDER_VERIFY_ACCOUNT_PATH||"/api/v1/verify-account";
export const PROVIDER_APPLY_PREMIUM_PATH=process.env.PROVIDER_APPLY_PREMIUM_PATH||"/api/v1/apply-premium";
export const PROVIDER_DIAGNOSTIC_SECRET=process.env.PROVIDER_DIAGNOSTIC_SECRET?.trim()||"";
export const PROVIDER_DELIVERY_WEBHOOK_ENABLED=Boolean(PROVIDER_DIAGNOSTIC_SECRET);
export const PORTAL_TOKEN_GENERATION_MODES=Object.freeze({"15_days":{label:"15 Hari",days:15},"30_days":{label:"30 Hari",days:30},permanent:{label:"Permanent",days:null}});
export const OWNER_WHATSAPP_URL=String(process.env.OWNER_WHATSAPP_URL||"").trim();
export const TOKEN_CENTER_URL=String(process.env.TOKEN_CENTER_URL||"").trim();
export const ECOSYSTEM_HANDOFF_SECRET=String(process.env.ECOSYSTEM_HANDOFF_SECRET||"").trim();
export const PROVIDER_TOKEN_ENCRYPTION_KEY=process.env.PROVIDER_TOKEN_ENCRYPTION_KEY?.trim()||"";
export const APP_RELEASE_PACKAGE="com.jyystore.jyyramprem";
export const APP_RELEASE_BUCKET="app-releases";
export const APP_RELEASE_MAX_BYTES=100*1024*1024;

if(PROVIDER_TOKEN_ENCRYPTION_KEY&&PROVIDER_TOKEN_ENCRYPTION_KEY.length<32)throw new Error("PROVIDER_TOKEN_ENCRYPTION_KEY harus minimal 32 karakter jika dikonfigurasi.");
if(!Number.isInteger(MAGIC_LINK_DAILY_LIMIT)||MAGIC_LINK_DAILY_LIMIT<1)throw new Error("MAGIC_LINK_DAILY_LIMIT harus berupa integer >= 1.");
if(!Number.isInteger(PROVIDER_DAILY_REQUEST_LIMIT)||PROVIDER_DAILY_REQUEST_LIMIT<1)throw new Error("PROVIDER_DAILY_REQUEST_LIMIT harus berupa integer >= 1.");
if(!Number.isInteger(PROVIDER_TIMEOUT_MS)||PROVIDER_TIMEOUT_MS<1000)throw new Error("PROVIDER_TIMEOUT_MS harus berupa integer >= 1000.");
if(!Number.isInteger(PROVIDER_MAX_RESPONSE_BYTES)||PROVIDER_MAX_RESPONSE_BYTES<1024||PROVIDER_MAX_RESPONSE_BYTES>10*1024*1024)throw new Error("PROVIDER_MAX_RESPONSE_BYTES harus integer 1024..10485760.");
if(!PROVIDER_SEND_MAGICLINK_PATH.startsWith("/api/v1/"))throw new Error("PROVIDER_SEND_MAGICLINK_PATH harus endpoint V1.");
if(!PROVIDER_VERIFY_ACCOUNT_PATH.startsWith("/api/v1/"))throw new Error("PROVIDER_VERIFY_ACCOUNT_PATH harus endpoint V1.");
if(!PROVIDER_APPLY_PREMIUM_PATH.startsWith("/api/v1/"))throw new Error("PROVIDER_APPLY_PREMIUM_PATH harus endpoint V1.");

export const PUBLIC_DIR=fileURLToPath(new URL("../../public/",import.meta.url));
